alias k='kubectl'
alias top='atop'
alias o='ssh'
alias ..='cd ..'
alias update='sudo apt update; sudo snap refresh --list'
alias upgrade='sudo apt upgrade; sudo snap refresh'
alias cpuinfo='cat /proc/cpuinfo'
alias performance='sudo cpufreqctl --governor --set=performance'
alias balance='sudo cpufreqctl --governor --set=ondemand'